### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by farshidtz** [SubChord/go-sse#1]
Hi,

Could you please add a license to this project? 

I'd like to use and contribute to it, but I can't do so unless it has an open source license.

Thanks

**Comment by thijsvdbb** [comment]
Done :)

**Comment by farshidtz** [comment]
Thanks, I was hoping it would be a permissive license such as MIT or Apache 2. 

The terms of GPL-3 are not ideal for open source projects (especially those with an existing non-GPL license) who would want to include this library:
> Permissions of this strong **copyleft** license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, **under the same license**.

**Comment by thijsvdbb** [comment]
Changed the license to MIT
