### ISSUE TITLE
issue in payload parsing

### ISSUE THREAD

**Issue by phil535** [SubChord/go-sse#9]
The payload is not parsed at all, as strings.SplitN with n=1 does not split at all.

https://github.com/SubChord/go-sse/blob/28e2f17bd096b3d433bfe6d4d3a020799bbf5ebc/sse_feed.go#L157

The following  should do the job and works for me: `split := strings.SplitN(payload, ":", 2) `

**Comment by thijsvdbb** [comment]
fixed in v1.0.7-rc
